#!/usr/bin/env python
#   This file is part of nexdatas - Tango Server for NeXus data writer
#
#    Copyright (C) 2012-2013 DESY, Jan Kotanski <jkotan@mail.desy.de>
#
#    nexdatas is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    nexdatas is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with nexdatas.  If not, see <http://www.gnu.org/licenses/>.
## \package ndtstools tools for ndts
## \file nxscreate_client_ds
# datasource creator

""" CLIENT datasource creator """

import sys

from optparse import OptionParser

from nxstools.nxsxml import (XMLFile, NDSource)
from nxstools.nxsdevicetools import (
    storeDataSource, checkServer, generateDeviceNames)

PYTANGO = False
try:
    import PyTango
    PYTANGO = True
except:
    pass


## creates CLIENT datasource file
# \param name device name
# \param directory output file directory
# \param fileprefix file name prefix
def createDataSource(name, directory, fileprefix, server, dsname=None):
    dname = name if not dsname else dsname
    df = XMLFile("%s/%s%s.ds.xml" % (directory, fileprefix, dname))
    print "%s/%s%s.ds.xml" % (directory, fileprefix, dname)
    sr = NDSource(df)
    sr.initClient(dname, name)
    if server:
        xml = df.prettyPrint()
        storeDataSource(dname, xml, server)
    else:
        df.dump()


def createParser():
    ## usage example
    usage = "usage: %prog [options] [name1] [name2]"
    ## option parser
    parser = OptionParser(usage=usage)

    parser.add_option("-p", "--device-prefix", type="string",
                      help="device prefix, i.e. exp_c",
                      dest="device", default="")
    parser.add_option("-f", "--first",
                      help="first index",
                      dest="first", default="1")
    parser.add_option("-l", "--last",
                      help="last index",
                      dest="last", default=None)

    parser.add_option("-d", "--directory", type="string",
                      help="output datasource directory",
                      dest="directory", default=".")
    parser.add_option("-x", "--file-prefix", type="string",
                      help="file prefix, i.e. counter",
                      dest="file", default="")

    parser.add_option("-s", "--datasource-prefix", type="string",
                      help="datasource prefix, i.e. counter",
                      dest="dsource", default="")

    parser.add_option("-b", "--database",  action="store_true",
                      default=False, dest="database",
                      help="store components in Configuration Server database")
    parser.add_option("-m", "--minimal_device",  action="store_true",
                      default=False, dest="minimal",
                      help="device name without first '0'")

    parser.add_option("-r", "--server", dest="server",
                      help="configuration server device name")

    return parser


## the main function
def main():

    parser = createParser()
    (options, args) = parser.parse_args()

    if options.database and not options.server:
        if not PYTANGO:
            print >> sys.stderr, "CollCompCreator No PyTango installed\n"
            parser.print_help()
            sys.exit(255)

        options.server = checkServer()
        if not options.server:
            parser.print_help()
            print ""
            sys.exit(0)

    if options.database:
        print "CONFIG SERVER:", options.server
    else:
        print "OUTPUT DIRECTORY:", options.directory

    dsargs = None
    aargs = []
    if options.device.strip():
        try:
            first = int(options.first)
        except:
            print >> sys.stderr, "ClientDSCreator: Invalid --first parameter\n"
            parser.print_help()
            sys.exit(255)

        try:
            last = int(options.last)
        except:
            print >> sys.stderr, "ClientDSCreator: Invalid --last parameter\n"
            parser.print_help()
            sys.exit(255)

        aargs = generateDeviceNames(options.device, first, last,
                                    options.minimal)

        if options.dsource:
            dsaargs = generateDeviceNames(
                options.dsource, first, last)
            dsargs = list(args) + dsaargs

    args += aargs
    if not dsargs:
        dsargs = args
    if not len(args):
        parser.print_help()
        sys.exit(255)

    for i in range(len(args)):
        if not options.database:
            print "CREATING: %s%s.ds.xml" % (options.file, dsargs[i])
        else:
            print "STORING: %s" % (dsargs[i])
        createDataSource(
            args[i], options.directory, options.file,
            options.server if options.database else None,
            dsargs[i])


if __name__ == "__main__":
    main()
