#!/usr/bin/env python
import os
import sys

commands = [
    "onlineds",
    "onlinecp",
    "clientds",
    "tangods",
    "deviceds",
    "comp"
]

if len(sys.argv) < 2 or sys.argv[1] not in commands:
    message = "Usage: nxscreate <command> [options]" \
        + " [<arg1> [<arg2> ... ] ] \n\n" \
        + "Commands:\n\n" \
        + "    clientds \n" \
        + "         create client datasources \n\n" \
        + "    tangods \n" \
        + "         create tango datasources \n\n" \
        + "    deviceds \n" \
        + "         create datasources for all device attributes \n\n" \
        + "    onlineds \n" \
        + "         create datasources from online.xml file \n\n" \
        + "    onlinecp \n" \
        + "         create component from online.xml file \n\n" \
        + "    comp \n" \
        + "         create simple components \n\n"

    print(message)
else:
    cmd = sys.argv[1]
    os.system("%s/ndtscreate_%s %s" % (
        os.path.dirname(os.path.realpath(__file__)),
        cmd,
        ' '.join("'%s'" % arg.replace("'", "\\'")
                 for arg in sys.argv[2:])))
